title: EnergyModelsUK
description: >- # this means to ignore newlines until "baseurl:"
  EnergyModelsUK blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  EnergyModelsUK

# Build settings
markdown: kramdown
theme: minima
permalink: pretty
future: true
google_analytics: G-P6ZWGPV945
